### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by tea-kostic** [hartwigmedical/gridss-purple-linx#22]
Hi,

I am having an issue with the Dockerfile. When I try to build the image, I get the following error:

_Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/opt/gridss-purple-linx/gridss-purple-linx.sh\": stat /opt/gridss-purple-linx/gridss-purple-linx.sh: no such file or directory": unknown._

Do you have any suggestions on how to build it to work? I tried multiple ways, but nothing seems to work. 

Also, do you suggest using gridss-purple-linx stand-alone or building each(Amber, Cobalt, Purple,...)separately? What's the difference and what would you recommend?

Thanks,
Tea

**Comment by alexiswl** [comment]
> Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: "/opt/gridss-purple-linx/gridss-purple-linx.sh": stat /opt/gridss-purple-linx/gridss-purple-linx.sh: no such file or directory": unknown.

How have you tried to build the Dockerfile?  
I would say this is a documentation issue. To build the docker container I would recommend using the following commands
```
# Change into a new tmp folder
cd $(mktemp -d)
# Clone this repo
git clone https://github.com/hartwigmedical/gridss-purple-linx/
# Change package.sh into an executable
chmod +x package.sh
# Run the build.sh script
# This will build the docker container for you
bash build.sh
# Change back to the top directory
cd ../
# Delete the repo
rm -rf gridss-purple-linx/
```

You can also just download the docker container from dockerhub
```
# Pull the latest version
docker pull gridss/gridss-purple-linx:latest
# Pull a specific version
docker pull gridss/gridss-purple-linx:1.3.2
```

> Also, do you suggest using gridss-purple-linx stand-alone or building each(Amber, Cobalt, Purple,...)separately? What's the difference and what would you recommend?

The `gridss-purple-linx.sh` script calls the `.jar` of each of Amber, Cobalt etc, so turning them into their own dockerfiles is not helpful here since all jars will need to be inside the one container. You can also find existing containers for each of them in the `quay.io` repo, see below:

* https://quay.io/repository/biocontainers/hmftools-amber
* https://quay.io/repository/biocontainers/hmftools-purple
* https://quay.io/repository/biocontainers/hmftools-cobalt
* https://quay.io/repository/biocontainers/hmftools-linx

However, if you are familiar with workflow languages, I am working on a step-version of this pipeline on [my fork](https://github.com/alexiswl/gridss-purple-linx/tree/cwl-workflow/cwl)

**Comment by d-cameron** [comment]
>Also, do you suggest using gridss-purple-linx stand-alone or building each(Amber, Cobalt, Purple,...)separately? What's the difference and what would you recommend?

gridss-purple-linx is a convenience wrapper around the SV/CN analysis portion of the Hartwig pipeline. There's no difference between running it, and running each of the tools with the same parameters.

> building each

I do not recommend building anything from source. We have release packages/jars for all tools. The entire gridss-purple-linx repository is just the `gridss-purple-linx.sh` wrapper and associated release packaging and regression testing scripts. The release packaging script doesn't actually do any building - it just downloads a specific release package version for each of the tools used (see `package.sh`).

While you can roll your own, `gridss-purple-linx.sh` is the recommended way of performing SV/CN analysis. If you just get/build the latest versions you may encounter errors caused by version mismatches between the various tools (e.g. GRIDSS is on a separate release cycle and if the latest version of GRIDSS results in a change in the output format, we'll need to update PURPLE and/or LINX to handle this). If you have specific HPC needs (e.g. you can improve resource utilisation/reduce cloud compute cost by sizing each step in an appropriately sized instance) then it makes sense to not use the wrapper script, but the only reasons for actually rebuilding anything is if you're creating your own fork (we welcome PRs), or have an urgent need for a bugfix that isn't yet in a release version.

**Comment by anapopicsbg** [comment]
Hi @alexiswl and @d-cameron. Thank you  for developing these amazing tools. We have used your tools for many SV/CNV related projects, and we  are  very satisfied with the results.

We are also working on a step-version of GRIDSS-PURPLE-LINX pipeline and implementing it in CWL. Many researchers  have expressed their interest in this pipeline, and we are now trying to make it available on the [Cancer Genomics Cloud.](https://www.cancergenomicscloud.org/) We were very happy to see that the CWL implementation is available. We were able to port your CWL version, and we are currently running tests.

We believe that there is no  better way to port new workflows on CGC than using the CWL created by tool’s authors. If you are interested, we could help  you with testing and finishing the workflow in CWL, and publishing it in the Cancer genomics cloud.

Once again, thank you for creating these powerful tools.
Best,

Ana Popic

**Comment by alexiswl** [comment]
Hi Ana,

I can touch up some of documentation / commands on my fork. I've managed to get it to run successfully through AWS Parallel Cluster through toil with the slurm scheduling system.  

@d-cameron is the owner and maintainer of gridss. I created the Dockerfile for umccr/gridss-cwl image since the ENTRYPOINT is set to the `gridss.sh` script in gridss/gridss docker image. 

The `gridss-cwl` Dockerfile uses `gridss/gridss` as a base, installs tabix (so the output vcf can be indexed) and rsync and then resets the entrypoint to null.
Unfortunately, there is no way to define the entrypoint or override the entrypoint in CWL, so this is a necessary step to ensure the workflow works over all endpoints.  

Daniel, I can put in a separate feature request for the installation of tabix in the Dockerfile and indexing of the output vcf file within `gridss.sh`. Do you think it would be possible to have the docker image tag suffix `-cwl` in addition to the standard Dockerfile where the `-cwl` suffix resets the entrypoint to null?

Alexis.

**Comment by alexiswl** [comment]
Index feature request: https://github.com/PapenfussLab/gridss/issues/441

Gridss image as CWL feature request: https://github.com/PapenfussLab/gridss/issues/442

Having watched through the gridss logs and studied the scripts there would be some benefit for also having gridss as a workflow.  The for loop for the preparation of each bam can take a few hours and would benefit from being sped up through a scatter of parallel processes.

**Comment by d-cameron** [comment]
There is definitely a resource utilisation benefit to having different GRIDSS steps in their own workflow. I have an [example torque wrapper script](https://github.com/PapenfussLab/gridss/blob/master/example/torque_example.sh) but it would be nice to be able to codify this in a more workflow-friendly manner. GRIDSS is actually quite parallelisation friendly and the latest version supports batching as well as parallelisation of the assembly step (the most time-consuming one). On my local HPC, we're running the assembly step across 16 jobs (8core/32gb each) with smaller job definitions for the other stages.

@alexiswl what's your thoughts on the current state of bioinformatics workflows? I've had a look at CWL, WDL, Nextflow, Snakemake, bcbio, BioNix, and a few others and the last time I checked, there didn't seem to be much of a consensus in the community on what to do. I'm not really keen on either maintaining multiple workflow definitions for different managers, each of which need to get per-environment customisation by the user anyway but I am interested in creating and maintaining a generic definitions that would simplify usage within a workflow. How well does a CWL tools definition fit this? Would creating a generic set of task definitions (or in the case of GRIDSS, a hierarchy of tasks) work for most workflow use cases?

**Comment by ohofmann** [comment]
I'd argue having one workflow language implementation is sufficient - it can serve as a reference implementation for others. CWL likely has the benefit of being fairly widely used even by engines that have been developed for other reasons (e.g., Cromwell's CWL support).

**Comment by alexiswl** [comment]
This is the current blueprint in order to generate gridss as a CWL workflow:

![](https://lucid.app/publicSegments/view/86af951a-8fd6-49b6-b3fc-80b8103479ad/image.png)

The following CWL subworkflows are required:
* BAM Preprocessing
* Breakend Assembly
* Variant Calling And Annotation

With the following CWL tools also required:
* Annotate Inserted Sequence
* Annotate Variants
* Collect Gridss Metrics
* Collect Gridss Metrics and Extract SV Reads | Samtools
* Identify Variants
* Prepare Reference
* Sanity Checking
* Soft Clips to Split Reads

This would also make the following assumptions:
* The input bam has been aligned with short read fastqs only / (short-read insert size)
* The execution end-point is able to use CWL v1.2 conditional logic (`when` and `pick_value`) - see the [CWL Change Log](https://www.commonwl.org/v1.2/Workflow.html#Changelog) for more info on these
