### ISSUE TITLE
Some detail about the input

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/gridss-purple-linx#30]
First of all, thank you for the extremely useful methods!

I have some question about the inputs to run the GRIDSS/PURPLE/LINX toolkit with Docker.

1) Our alignment files are CRAM format , could I convert the CRAM files to FIFO special files by Sentieon (https://support.sentieon.com/manual/usages/general/#util-binary) as input:
     sentieon util stream -i INPUT.cram -q RECAL_TABLE --output_index_file OUTPUT.bam.bai -o OUTPUT.bam

2) The alignment were performanced by BWA mem with '-M' to hg38 with all ALT contigs, will thhes proper for the toolkit.

Thanks

**Comment by d-cameron** [comment]
>CRAM

CRAM support is limited to single-threaded processing as the htsjdk library we use does not have multithreaded CRAM support. It also depends on which version of CRAM your file is in as htsjdk does not yet fully support the latest version of CRAM. Transcoding to BAM is strongly recommended. Unlink SNV calling, BQSR has minimal impact on SV calling.

> `bwa mem -M`

The `-M` option of bwa is for backwards compatability for old tools that do not support the supplementary alignment flag. It hasn't been part of the GATK best practices for many years and I continue to be surprised by the number of users that still use it.

That said, it is a supported configuration. As part of it's pre-processing step, GRIDSS rewrites the secondsary/supplementary alignment flags to fix the issue with split read alignments not conforming to the SAM specifications due to the use of `bwa mem -M`.

> hg38 with all ALT contigs

PURPLE/LINX assume that hg38 alignments are against the Broad `Homo_sapiens_assembly38.fasta` version of hg38. While it'll probably run if this is not the case, using other references is not officially supported by the GRIDSS/PURPLE/LINX pipeline.
